### PR TITLE
fix(text-field): support v-model.number

### LINKED ISSUE #515: Invalid prop: type check failed when using m-text-field and numbers
**Describe the bug**
m-text-field v-model.number not handled correctly and throws error:
`[Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "0", got Number with value 0.`

**To Reproduce**

ParentComponent.vue
```
<ChildComponent v-for="position in postData.positions" :key="position.id" :position="position" />
```

ChildComponent.vue
```
<m-text-field v-model.number="position.net" type="number" :id="'pg'+position.id">
                    <m-floating-label for="my-text-field">Net/€</m-floating-label>
                    <m-line-ripple slot="bottomLine"/>
                </m-text-field> 

props: {
        position: {
            title:{type: String},
            id: {type: Number},
            net: {type: Number, default:0},
            amount: {type: Number, default: 0},
        },
    },
}
```

**Expected behaviour**
`m-text-field` with `type="text/number/date/...etc"` and `v-model` should work like `<input type="text/number/date/...etc" />`

**Additional context**
Using `<input type="number" v-model.number="position.net" />` works as expected. 
Even if I ommit ` v-model.number` for ` v-model`, it's not working.

### PR DESCRIPTION
**Pull request by tychenjiajun**
fix: add default injection for icon, character counter and helper text

fixes #515

### CODE REVIEW

File: components/text-field/TextField.vue [hunk 1]
```diff
@@ -128,20 +128,23 @@ export default {
...
       }
+    },
+    val () {
+      return String(this.value)
     }
   },
   watch: {
-    useNativeValidation () {
-      this.mdcTextField.useNativeValidation = this.useNativeValidation
+    useNativeValidation (v) {
```
Comment (matsp) [inline components/text-field/TextField.vue]: Please use readable variable names.
